### ISSUE TITLE
Using 'microk8s' on Ubuntu 18.04, getting 'Error: This command needs 1 argument: chart name'

### ISSUE THREAD

**Issue by ksaye** [microsoft/iotedge-k8s-doc#3]
Running on Ubuntu 18.04 on x64, I am getting the error 'Error: This command needs 1 argument: chart name' when I try to run step 3 of: https://microsoft.github.io/iotedge-k8s-doc/examples/helloworld.html as shown below:

```
root@up1:~# uname -a
Linux up1 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@up1:~# microk8s status
microk8s is running
addons:
dns: enabled
helm: enabled
storage: enabled
cilium: disabled
dashboard: disabled
fluentd: disabled
gpu: disabled
helm3: disabled
host-access: disabled
ingress: disabled
istio: disabled
jaeger: disabled
knative: disabled
kubeflow: disabled
linkerd: disabled
metallb: disabled
metrics-server: disabled
prometheus: disabled
rbac: disabled
registry: disabled
root@up1:~# microk8s helm install --repo https://edgek8s.blob.core.windows.net/staging edge-crd edge-kubernetes-crd
Error: This command needs 1 argument: chart name
```

My install process:

1. install 18.04 Ubuntu on a x64 physical host.
2. snap install microk8s --classic
3. export PATH=/snap/bin:$PATH
4. microk8s enable dns storage helm kubectl
5. microk8s helm init
6. microk8s kubectl create ns helloworld
7. microk8s helm install --repo https://edgek8s.blob.core.windows.net/staging edge-crd edge-kubernetes-crd

**Comment by veyalla** [comment]
According to https://microk8s.io/docs/addons the helm addon installs Helm 2. 

As noted in [prerequisites](https://microsoft.github.io/iotedge-k8s-doc/examples/prereqs.html#helm-3) Helm 3 is required for the tutorials. 

In general, we've not tested this in microk8s so YMMV, even after you fix the Helm version issue. This [lab](https://labs.iotedge.dev/codelabs/deploy-iotedge-k8s/index.html?index=..%2F..index#0) runs through setting this in an Azure Ubuntu VM if you're interested.
