### ISSUE TITLE
We might to offer how to install Helm in the docs.. 

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/iotedge-k8s-doc#4]
# sudo apt-get update
apt-get upgrade

# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
# ls get*.sh
get_helm.sh
# chmod 700 get_helm.sh
# ./get_helm.sh
Downloading https://get.helm.sh/helm-v3.2.3-linux-amd64.tar.gz
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm

**Comment by veyalla** [comment]
Thanks for the suggestion. Users may prefer to install Helm on Windows, Linux or Mac using their preferred package manager, so best to point to Helm’s official installation docs.
